// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.15.8
// source: finsim.proto

package finsimpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identity_Login_FullMethodName          = "/finsim.Identity/Login"
	Identity_Logout_FullMethodName         = "/finsim.Identity/Logout"
	Identity_ChangePassword_FullMethodName = "/finsim.Identity/ChangePassword"
	Identity_AddMFA_FullMethodName         = "/finsim.Identity/AddMFA"
	Identity_RemoveMFA_FullMethodName      = "/finsim.Identity/RemoveMFA"
	Identity_UpdateProfile_FullMethodName  = "/finsim.Identity/UpdateProfile"
)

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityClient interface {
	Login(ctx context.Context, in *LoginArg, opts ...grpc.CallOption) (*LoginResult, error)
	Logout(ctx context.Context, in *LogoutArg, opts ...grpc.CallOption) (*LogoutResult, error)
	ChangePassword(ctx context.Context, in *ChangePasswordArg, opts ...grpc.CallOption) (*ChangePasswordResult, error)
	AddMFA(ctx context.Context, in *AddMFAArg, opts ...grpc.CallOption) (*AddMFAResult, error)
	RemoveMFA(ctx context.Context, in *RemoveMFAArg, opts ...grpc.CallOption) (*RemoveMFAResult, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileArg, opts ...grpc.CallOption) (*UpdateProfileResult, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) Login(ctx context.Context, in *LoginArg, opts ...grpc.CallOption) (*LoginResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, Identity_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Logout(ctx context.Context, in *LogoutArg, opts ...grpc.CallOption) (*LogoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResult)
	err := c.cc.Invoke(ctx, Identity_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) ChangePassword(ctx context.Context, in *ChangePasswordArg, opts ...grpc.CallOption) (*ChangePasswordResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResult)
	err := c.cc.Invoke(ctx, Identity_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) AddMFA(ctx context.Context, in *AddMFAArg, opts ...grpc.CallOption) (*AddMFAResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMFAResult)
	err := c.cc.Invoke(ctx, Identity_AddMFA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) RemoveMFA(ctx context.Context, in *RemoveMFAArg, opts ...grpc.CallOption) (*RemoveMFAResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMFAResult)
	err := c.cc.Invoke(ctx, Identity_RemoveMFA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) UpdateProfile(ctx context.Context, in *UpdateProfileArg, opts ...grpc.CallOption) (*UpdateProfileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResult)
	err := c.cc.Invoke(ctx, Identity_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
// All implementations must embed UnimplementedIdentityServer
// for forward compatibility.
type IdentityServer interface {
	Login(context.Context, *LoginArg) (*LoginResult, error)
	Logout(context.Context, *LogoutArg) (*LogoutResult, error)
	ChangePassword(context.Context, *ChangePasswordArg) (*ChangePasswordResult, error)
	AddMFA(context.Context, *AddMFAArg) (*AddMFAResult, error)
	RemoveMFA(context.Context, *RemoveMFAArg) (*RemoveMFAResult, error)
	UpdateProfile(context.Context, *UpdateProfileArg) (*UpdateProfileResult, error)
	mustEmbedUnimplementedIdentityServer()
}

// UnimplementedIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServer struct{}

func (UnimplementedIdentityServer) Login(context.Context, *LoginArg) (*LoginResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIdentityServer) Logout(context.Context, *LogoutArg) (*LogoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedIdentityServer) ChangePassword(context.Context, *ChangePasswordArg) (*ChangePasswordResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedIdentityServer) AddMFA(context.Context, *AddMFAArg) (*AddMFAResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMFA not implemented")
}
func (UnimplementedIdentityServer) RemoveMFA(context.Context, *RemoveMFAArg) (*RemoveMFAResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMFA not implemented")
}
func (UnimplementedIdentityServer) UpdateProfile(context.Context, *UpdateProfileArg) (*UpdateProfileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedIdentityServer) mustEmbedUnimplementedIdentityServer() {}
func (UnimplementedIdentityServer) testEmbeddedByValue()                  {}

// UnsafeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServer will
// result in compilation errors.
type UnsafeIdentityServer interface {
	mustEmbedUnimplementedIdentityServer()
}

func RegisterIdentityServer(s grpc.ServiceRegistrar, srv IdentityServer) {
	// If the following call panics, it indicates UnimplementedIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identity_ServiceDesc, srv)
}

func _Identity_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Login(ctx, req.(*LoginArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Logout(ctx, req.(*LogoutArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ChangePassword(ctx, req.(*ChangePasswordArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_AddMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMFAArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).AddMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_AddMFA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).AddMFA(ctx, req.(*AddMFAArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_RemoveMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMFAArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).RemoveMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_RemoveMFA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).RemoveMFA(ctx, req.(*RemoveMFAArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).UpdateProfile(ctx, req.(*UpdateProfileArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Identity_ServiceDesc is the grpc.ServiceDesc for Identity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Identity_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Identity_Logout_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Identity_ChangePassword_Handler,
		},
		{
			MethodName: "AddMFA",
			Handler:    _Identity_AddMFA_Handler,
		},
		{
			MethodName: "RemoveMFA",
			Handler:    _Identity_RemoveMFA_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Identity_UpdateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	Admin_ListParticipants_FullMethodName  = "/finsim.Admin/ListParticipants"
	Admin_AddParticipant_FullMethodName    = "/finsim.Admin/AddParticipant"
	Admin_RemoveParticipant_FullMethodName = "/finsim.Admin/RemoveParticipant"
	Admin_ModifyParticipant_FullMethodName = "/finsim.Admin/ModifyParticipant"
	Admin_ModifyEconomy_FullMethodName     = "/finsim.Admin/ModifyEconomy"
	Admin_RequestSupport_FullMethodName    = "/finsim.Admin/RequestSupport"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	ListParticipants(ctx context.Context, in *ListParticipantsArg, opts ...grpc.CallOption) (*ListParticipantsResult, error)
	AddParticipant(ctx context.Context, in *AddParticipantArg, opts ...grpc.CallOption) (*AddParticipantResult, error)
	RemoveParticipant(ctx context.Context, in *RemoveParticipantArg, opts ...grpc.CallOption) (*RemoveParticipantResult, error)
	ModifyParticipant(ctx context.Context, in *ModifyParticipantArg, opts ...grpc.CallOption) (*ModifyParticipantResult, error)
	ModifyEconomy(ctx context.Context, in *ModifyEconomyArg, opts ...grpc.CallOption) (*ModifyEconomyResult, error)
	RequestSupport(ctx context.Context, in *RequestSupportArg, opts ...grpc.CallOption) (*RequestSupportResult, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ListParticipants(ctx context.Context, in *ListParticipantsArg, opts ...grpc.CallOption) (*ListParticipantsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParticipantsResult)
	err := c.cc.Invoke(ctx, Admin_ListParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AddParticipant(ctx context.Context, in *AddParticipantArg, opts ...grpc.CallOption) (*AddParticipantResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddParticipantResult)
	err := c.cc.Invoke(ctx, Admin_AddParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantArg, opts ...grpc.CallOption) (*RemoveParticipantResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveParticipantResult)
	err := c.cc.Invoke(ctx, Admin_RemoveParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ModifyParticipant(ctx context.Context, in *ModifyParticipantArg, opts ...grpc.CallOption) (*ModifyParticipantResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyParticipantResult)
	err := c.cc.Invoke(ctx, Admin_ModifyParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ModifyEconomy(ctx context.Context, in *ModifyEconomyArg, opts ...grpc.CallOption) (*ModifyEconomyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyEconomyResult)
	err := c.cc.Invoke(ctx, Admin_ModifyEconomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RequestSupport(ctx context.Context, in *RequestSupportArg, opts ...grpc.CallOption) (*RequestSupportResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestSupportResult)
	err := c.cc.Invoke(ctx, Admin_RequestSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	ListParticipants(context.Context, *ListParticipantsArg) (*ListParticipantsResult, error)
	AddParticipant(context.Context, *AddParticipantArg) (*AddParticipantResult, error)
	RemoveParticipant(context.Context, *RemoveParticipantArg) (*RemoveParticipantResult, error)
	ModifyParticipant(context.Context, *ModifyParticipantArg) (*ModifyParticipantResult, error)
	ModifyEconomy(context.Context, *ModifyEconomyArg) (*ModifyEconomyResult, error)
	RequestSupport(context.Context, *RequestSupportArg) (*RequestSupportResult, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) ListParticipants(context.Context, *ListParticipantsArg) (*ListParticipantsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParticipants not implemented")
}
func (UnimplementedAdminServer) AddParticipant(context.Context, *AddParticipantArg) (*AddParticipantResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddParticipant not implemented")
}
func (UnimplementedAdminServer) RemoveParticipant(context.Context, *RemoveParticipantArg) (*RemoveParticipantResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedAdminServer) ModifyParticipant(context.Context, *ModifyParticipantArg) (*ModifyParticipantResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyParticipant not implemented")
}
func (UnimplementedAdminServer) ModifyEconomy(context.Context, *ModifyEconomyArg) (*ModifyEconomyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyEconomy not implemented")
}
func (UnimplementedAdminServer) RequestSupport(context.Context, *RequestSupportArg) (*RequestSupportResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSupport not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ListParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParticipantsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListParticipants(ctx, req.(*ListParticipantsArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AddParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AddParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AddParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AddParticipant(ctx, req.(*AddParticipantArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RemoveParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RemoveParticipant(ctx, req.(*RemoveParticipantArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ModifyParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyParticipantArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ModifyParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ModifyParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ModifyParticipant(ctx, req.(*ModifyParticipantArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ModifyEconomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyEconomyArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ModifyEconomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ModifyEconomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ModifyEconomy(ctx, req.(*ModifyEconomyArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RequestSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSupportArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RequestSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RequestSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RequestSupport(ctx, req.(*RequestSupportArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListParticipants",
			Handler:    _Admin_ListParticipants_Handler,
		},
		{
			MethodName: "AddParticipant",
			Handler:    _Admin_AddParticipant_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _Admin_RemoveParticipant_Handler,
		},
		{
			MethodName: "ModifyParticipant",
			Handler:    _Admin_ModifyParticipant_Handler,
		},
		{
			MethodName: "ModifyEconomy",
			Handler:    _Admin_ModifyEconomy_Handler,
		},
		{
			MethodName: "RequestSupport",
			Handler:    _Admin_RequestSupport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	Employer_PostJob_FullMethodName           = "/finsim.Employer/PostJob"
	Employer_RemoveJobPosting_FullMethodName  = "/finsim.Employer/RemoveJobPosting"
	Employer_TerminateEmployee_FullMethodName = "/finsim.Employer/TerminateEmployee"
)

// EmployerClient is the client API for Employer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployerClient interface {
	PostJob(ctx context.Context, in *PostJobArg, opts ...grpc.CallOption) (*PostJobResult, error)
	RemoveJobPosting(ctx context.Context, in *RemoveJobPostingArg, opts ...grpc.CallOption) (*RemoveJobPostingResult, error)
	TerminateEmployee(ctx context.Context, in *TerminateEmployeeArg, opts ...grpc.CallOption) (*TerminateEmployeeResult, error)
}

type employerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployerClient(cc grpc.ClientConnInterface) EmployerClient {
	return &employerClient{cc}
}

func (c *employerClient) PostJob(ctx context.Context, in *PostJobArg, opts ...grpc.CallOption) (*PostJobResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostJobResult)
	err := c.cc.Invoke(ctx, Employer_PostJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employerClient) RemoveJobPosting(ctx context.Context, in *RemoveJobPostingArg, opts ...grpc.CallOption) (*RemoveJobPostingResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveJobPostingResult)
	err := c.cc.Invoke(ctx, Employer_RemoveJobPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employerClient) TerminateEmployee(ctx context.Context, in *TerminateEmployeeArg, opts ...grpc.CallOption) (*TerminateEmployeeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateEmployeeResult)
	err := c.cc.Invoke(ctx, Employer_TerminateEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployerServer is the server API for Employer service.
// All implementations must embed UnimplementedEmployerServer
// for forward compatibility.
type EmployerServer interface {
	PostJob(context.Context, *PostJobArg) (*PostJobResult, error)
	RemoveJobPosting(context.Context, *RemoveJobPostingArg) (*RemoveJobPostingResult, error)
	TerminateEmployee(context.Context, *TerminateEmployeeArg) (*TerminateEmployeeResult, error)
	mustEmbedUnimplementedEmployerServer()
}

// UnimplementedEmployerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployerServer struct{}

func (UnimplementedEmployerServer) PostJob(context.Context, *PostJobArg) (*PostJobResult, error) {
	return nil, status.Error(codes.Unimplemented, "method PostJob not implemented")
}
func (UnimplementedEmployerServer) RemoveJobPosting(context.Context, *RemoveJobPostingArg) (*RemoveJobPostingResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveJobPosting not implemented")
}
func (UnimplementedEmployerServer) TerminateEmployee(context.Context, *TerminateEmployeeArg) (*TerminateEmployeeResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateEmployee not implemented")
}
func (UnimplementedEmployerServer) mustEmbedUnimplementedEmployerServer() {}
func (UnimplementedEmployerServer) testEmbeddedByValue()                  {}

// UnsafeEmployerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployerServer will
// result in compilation errors.
type UnsafeEmployerServer interface {
	mustEmbedUnimplementedEmployerServer()
}

func RegisterEmployerServer(s grpc.ServiceRegistrar, srv EmployerServer) {
	// If the following call panics, it indicates UnimplementedEmployerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Employer_ServiceDesc, srv)
}

func _Employer_PostJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostJobArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployerServer).PostJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employer_PostJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployerServer).PostJob(ctx, req.(*PostJobArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employer_RemoveJobPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobPostingArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployerServer).RemoveJobPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employer_RemoveJobPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployerServer).RemoveJobPosting(ctx, req.(*RemoveJobPostingArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employer_TerminateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateEmployeeArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployerServer).TerminateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employer_TerminateEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployerServer).TerminateEmployee(ctx, req.(*TerminateEmployeeArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Employer_ServiceDesc is the grpc.ServiceDesc for Employer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Employer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Employer",
	HandlerType: (*EmployerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostJob",
			Handler:    _Employer_PostJob_Handler,
		},
		{
			MethodName: "RemoveJobPosting",
			Handler:    _Employer_RemoveJobPosting_Handler,
		},
		{
			MethodName: "TerminateEmployee",
			Handler:    _Employer_TerminateEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	Employee_SearchJobs_FullMethodName  = "/finsim.Employee/SearchJobs"
	Employee_ApplyForJob_FullMethodName = "/finsim.Employee/ApplyForJob"
	Employee_QuitJob_FullMethodName     = "/finsim.Employee/QuitJob"
)

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeClient interface {
	SearchJobs(ctx context.Context, in *SearchJobsArg, opts ...grpc.CallOption) (*SearchJobsResult, error)
	ApplyForJob(ctx context.Context, in *ApplyForJobArg, opts ...grpc.CallOption) (*ApplyForJobResult, error)
	QuitJob(ctx context.Context, in *QuitJobArg, opts ...grpc.CallOption) (*QuitJobResult, error)
}

type employeeClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeClient(cc grpc.ClientConnInterface) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) SearchJobs(ctx context.Context, in *SearchJobsArg, opts ...grpc.CallOption) (*SearchJobsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchJobsResult)
	err := c.cc.Invoke(ctx, Employee_SearchJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) ApplyForJob(ctx context.Context, in *ApplyForJobArg, opts ...grpc.CallOption) (*ApplyForJobResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyForJobResult)
	err := c.cc.Invoke(ctx, Employee_ApplyForJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) QuitJob(ctx context.Context, in *QuitJobArg, opts ...grpc.CallOption) (*QuitJobResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuitJobResult)
	err := c.cc.Invoke(ctx, Employee_QuitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServer is the server API for Employee service.
// All implementations must embed UnimplementedEmployeeServer
// for forward compatibility.
type EmployeeServer interface {
	SearchJobs(context.Context, *SearchJobsArg) (*SearchJobsResult, error)
	ApplyForJob(context.Context, *ApplyForJobArg) (*ApplyForJobResult, error)
	QuitJob(context.Context, *QuitJobArg) (*QuitJobResult, error)
	mustEmbedUnimplementedEmployeeServer()
}

// UnimplementedEmployeeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeServer struct{}

func (UnimplementedEmployeeServer) SearchJobs(context.Context, *SearchJobsArg) (*SearchJobsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchJobs not implemented")
}
func (UnimplementedEmployeeServer) ApplyForJob(context.Context, *ApplyForJobArg) (*ApplyForJobResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyForJob not implemented")
}
func (UnimplementedEmployeeServer) QuitJob(context.Context, *QuitJobArg) (*QuitJobResult, error) {
	return nil, status.Error(codes.Unimplemented, "method QuitJob not implemented")
}
func (UnimplementedEmployeeServer) mustEmbedUnimplementedEmployeeServer() {}
func (UnimplementedEmployeeServer) testEmbeddedByValue()                  {}

// UnsafeEmployeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServer will
// result in compilation errors.
type UnsafeEmployeeServer interface {
	mustEmbedUnimplementedEmployeeServer()
}

func RegisterEmployeeServer(s grpc.ServiceRegistrar, srv EmployeeServer) {
	// If the following call panics, it indicates UnimplementedEmployeeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Employee_ServiceDesc, srv)
}

func _Employee_SearchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchJobsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).SearchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_SearchJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).SearchJobs(ctx, req.(*SearchJobsArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_ApplyForJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyForJobArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).ApplyForJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_ApplyForJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).ApplyForJob(ctx, req.(*ApplyForJobArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_QuitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitJobArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).QuitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_QuitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).QuitJob(ctx, req.(*QuitJobArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Employee_ServiceDesc is the grpc.ServiceDesc for Employee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Employee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchJobs",
			Handler:    _Employee_SearchJobs_Handler,
		},
		{
			MethodName: "ApplyForJob",
			Handler:    _Employee_ApplyForJob_Handler,
		},
		{
			MethodName: "QuitJob",
			Handler:    _Employee_QuitJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	Marketplace_Buy_FullMethodName            = "/finsim.Marketplace/Buy"
	Marketplace_SearchProducts_FullMethodName = "/finsim.Marketplace/SearchProducts"
)

// MarketplaceClient is the client API for Marketplace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketplaceClient interface {
	// Sell with a negative number.
	Buy(ctx context.Context, in *BuyArg, opts ...grpc.CallOption) (*BuyResult, error)
	SearchProducts(ctx context.Context, in *SearchProductsArg, opts ...grpc.CallOption) (*SearchProductsResult, error)
}

type marketplaceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceClient(cc grpc.ClientConnInterface) MarketplaceClient {
	return &marketplaceClient{cc}
}

func (c *marketplaceClient) Buy(ctx context.Context, in *BuyArg, opts ...grpc.CallOption) (*BuyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyResult)
	err := c.cc.Invoke(ctx, Marketplace_Buy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) SearchProducts(ctx context.Context, in *SearchProductsArg, opts ...grpc.CallOption) (*SearchProductsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResult)
	err := c.cc.Invoke(ctx, Marketplace_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceServer is the server API for Marketplace service.
// All implementations must embed UnimplementedMarketplaceServer
// for forward compatibility.
type MarketplaceServer interface {
	// Sell with a negative number.
	Buy(context.Context, *BuyArg) (*BuyResult, error)
	SearchProducts(context.Context, *SearchProductsArg) (*SearchProductsResult, error)
	mustEmbedUnimplementedMarketplaceServer()
}

// UnimplementedMarketplaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketplaceServer struct{}

func (UnimplementedMarketplaceServer) Buy(context.Context, *BuyArg) (*BuyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Buy not implemented")
}
func (UnimplementedMarketplaceServer) SearchProducts(context.Context, *SearchProductsArg) (*SearchProductsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedMarketplaceServer) mustEmbedUnimplementedMarketplaceServer() {}
func (UnimplementedMarketplaceServer) testEmbeddedByValue()                     {}

// UnsafeMarketplaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketplaceServer will
// result in compilation errors.
type UnsafeMarketplaceServer interface {
	mustEmbedUnimplementedMarketplaceServer()
}

func RegisterMarketplaceServer(s grpc.ServiceRegistrar, srv MarketplaceServer) {
	// If the following call panics, it indicates UnimplementedMarketplaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Marketplace_ServiceDesc, srv)
}

func _Marketplace_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_Buy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).Buy(ctx, req.(*BuyArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).SearchProducts(ctx, req.(*SearchProductsArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketplace_ServiceDesc is the grpc.ServiceDesc for Marketplace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketplace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Marketplace",
	HandlerType: (*MarketplaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Buy",
			Handler:    _Marketplace_Buy_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _Marketplace_SearchProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	AuctionHouse_Bid_FullMethodName     = "/finsim.AuctionHouse/Bid"
	AuctionHouse_Auction_FullMethodName = "/finsim.AuctionHouse/Auction"
)

// AuctionHouseClient is the client API for AuctionHouse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionHouseClient interface {
	Bid(ctx context.Context, in *BidArg, opts ...grpc.CallOption) (*BidResult, error)
	Auction(ctx context.Context, in *AuctionArg, opts ...grpc.CallOption) (*AuctionResult, error)
}

type auctionHouseClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionHouseClient(cc grpc.ClientConnInterface) AuctionHouseClient {
	return &auctionHouseClient{cc}
}

func (c *auctionHouseClient) Bid(ctx context.Context, in *BidArg, opts ...grpc.CallOption) (*BidResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidResult)
	err := c.cc.Invoke(ctx, AuctionHouse_Bid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionHouseClient) Auction(ctx context.Context, in *AuctionArg, opts ...grpc.CallOption) (*AuctionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuctionResult)
	err := c.cc.Invoke(ctx, AuctionHouse_Auction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionHouseServer is the server API for AuctionHouse service.
// All implementations must embed UnimplementedAuctionHouseServer
// for forward compatibility.
type AuctionHouseServer interface {
	Bid(context.Context, *BidArg) (*BidResult, error)
	Auction(context.Context, *AuctionArg) (*AuctionResult, error)
	mustEmbedUnimplementedAuctionHouseServer()
}

// UnimplementedAuctionHouseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionHouseServer struct{}

func (UnimplementedAuctionHouseServer) Bid(context.Context, *BidArg) (*BidResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionHouseServer) Auction(context.Context, *AuctionArg) (*AuctionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Auction not implemented")
}
func (UnimplementedAuctionHouseServer) mustEmbedUnimplementedAuctionHouseServer() {}
func (UnimplementedAuctionHouseServer) testEmbeddedByValue()                      {}

// UnsafeAuctionHouseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionHouseServer will
// result in compilation errors.
type UnsafeAuctionHouseServer interface {
	mustEmbedUnimplementedAuctionHouseServer()
}

func RegisterAuctionHouseServer(s grpc.ServiceRegistrar, srv AuctionHouseServer) {
	// If the following call panics, it indicates UnimplementedAuctionHouseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionHouse_ServiceDesc, srv)
}

func _AuctionHouse_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionHouseServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionHouse_Bid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionHouseServer).Bid(ctx, req.(*BidArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionHouse_Auction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionHouseServer).Auction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionHouse_Auction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionHouseServer).Auction(ctx, req.(*AuctionArg))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionHouse_ServiceDesc is the grpc.ServiceDesc for AuctionHouse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionHouse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.AuctionHouse",
	HandlerType: (*AuctionHouseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _AuctionHouse_Bid_Handler,
		},
		{
			MethodName: "Auction",
			Handler:    _AuctionHouse_Auction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	Brokerage_ExecuteOption_FullMethodName    = "/finsim.Brokerage/ExecuteOption"
	Brokerage_SearchSecurities_FullMethodName = "/finsim.Brokerage/SearchSecurities"
)

// BrokerageClient is the client API for Brokerage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Design decision:
// I think stocks, bonds, ETFs, etc. should take place in a separate brokerage
// service so that it models real life better.
type BrokerageClient interface {
	// Sell with a negative number.
	// rpc BuyStock (BuyStockArg) returns (BuyStockResult);
	ExecuteOption(ctx context.Context, in *ExecuteOptionArg, opts ...grpc.CallOption) (*ExecuteOptionResult, error)
	SearchSecurities(ctx context.Context, in *SearchSecuritiesArg, opts ...grpc.CallOption) (*SearchSecuritiesResult, error)
}

type brokerageClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerageClient(cc grpc.ClientConnInterface) BrokerageClient {
	return &brokerageClient{cc}
}

func (c *brokerageClient) ExecuteOption(ctx context.Context, in *ExecuteOptionArg, opts ...grpc.CallOption) (*ExecuteOptionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteOptionResult)
	err := c.cc.Invoke(ctx, Brokerage_ExecuteOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerageClient) SearchSecurities(ctx context.Context, in *SearchSecuritiesArg, opts ...grpc.CallOption) (*SearchSecuritiesResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSecuritiesResult)
	err := c.cc.Invoke(ctx, Brokerage_SearchSecurities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerageServer is the server API for Brokerage service.
// All implementations must embed UnimplementedBrokerageServer
// for forward compatibility.
//
// Design decision:
// I think stocks, bonds, ETFs, etc. should take place in a separate brokerage
// service so that it models real life better.
type BrokerageServer interface {
	// Sell with a negative number.
	// rpc BuyStock (BuyStockArg) returns (BuyStockResult);
	ExecuteOption(context.Context, *ExecuteOptionArg) (*ExecuteOptionResult, error)
	SearchSecurities(context.Context, *SearchSecuritiesArg) (*SearchSecuritiesResult, error)
	mustEmbedUnimplementedBrokerageServer()
}

// UnimplementedBrokerageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerageServer struct{}

func (UnimplementedBrokerageServer) ExecuteOption(context.Context, *ExecuteOptionArg) (*ExecuteOptionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteOption not implemented")
}
func (UnimplementedBrokerageServer) SearchSecurities(context.Context, *SearchSecuritiesArg) (*SearchSecuritiesResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSecurities not implemented")
}
func (UnimplementedBrokerageServer) mustEmbedUnimplementedBrokerageServer() {}
func (UnimplementedBrokerageServer) testEmbeddedByValue()                   {}

// UnsafeBrokerageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerageServer will
// result in compilation errors.
type UnsafeBrokerageServer interface {
	mustEmbedUnimplementedBrokerageServer()
}

func RegisterBrokerageServer(s grpc.ServiceRegistrar, srv BrokerageServer) {
	// If the following call panics, it indicates UnimplementedBrokerageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Brokerage_ServiceDesc, srv)
}

func _Brokerage_ExecuteOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteOptionArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerageServer).ExecuteOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Brokerage_ExecuteOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerageServer).ExecuteOption(ctx, req.(*ExecuteOptionArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brokerage_SearchSecurities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSecuritiesArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerageServer).SearchSecurities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Brokerage_SearchSecurities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerageServer).SearchSecurities(ctx, req.(*SearchSecuritiesArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Brokerage_ServiceDesc is the grpc.ServiceDesc for Brokerage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Brokerage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Brokerage",
	HandlerType: (*BrokerageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOption",
			Handler:    _Brokerage_ExecuteOption_Handler,
		},
		{
			MethodName: "SearchSecurities",
			Handler:    _Brokerage_SearchSecurities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	Messaging_SendMessage_FullMethodName     = "/finsim.Messaging/SendMessage"
	Messaging_ReceiveMessages_FullMethodName = "/finsim.Messaging/ReceiveMessages"
	Messaging_DeleteMessage_FullMethodName   = "/finsim.Messaging/DeleteMessage"
	Messaging_ReadMessage_FullMethodName     = "/finsim.Messaging/ReadMessage"
)

// MessagingClient is the client API for Messaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TODO: Should this API even do messaging? It seems like messaging should be
// handled in some other way, or just entirely out-of-band.
// I don't think messaging should even be a part of this in any way.
// Defining a messaging protocol in here is bloat. Using an external messaging
// protocol means double-authentication and increased attack surface.
type MessagingClient interface {
	SendMessage(ctx context.Context, in *SendMessageArg, opts ...grpc.CallOption) (*SendMessageResult, error)
	ReceiveMessages(ctx context.Context, in *ReceiveMessagesArg, opts ...grpc.CallOption) (*ReceiveMessagesResult, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageArg, opts ...grpc.CallOption) (*DeleteMessageResult, error)
	ReadMessage(ctx context.Context, in *ReadMessageArg, opts ...grpc.CallOption) (*ReadMessageResult, error)
}

type messagingClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagingClient(cc grpc.ClientConnInterface) MessagingClient {
	return &messagingClient{cc}
}

func (c *messagingClient) SendMessage(ctx context.Context, in *SendMessageArg, opts ...grpc.CallOption) (*SendMessageResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResult)
	err := c.cc.Invoke(ctx, Messaging_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) ReceiveMessages(ctx context.Context, in *ReceiveMessagesArg, opts ...grpc.CallOption) (*ReceiveMessagesResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveMessagesResult)
	err := c.cc.Invoke(ctx, Messaging_ReceiveMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) DeleteMessage(ctx context.Context, in *DeleteMessageArg, opts ...grpc.CallOption) (*DeleteMessageResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResult)
	err := c.cc.Invoke(ctx, Messaging_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) ReadMessage(ctx context.Context, in *ReadMessageArg, opts ...grpc.CallOption) (*ReadMessageResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMessageResult)
	err := c.cc.Invoke(ctx, Messaging_ReadMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagingServer is the server API for Messaging service.
// All implementations must embed UnimplementedMessagingServer
// for forward compatibility.
//
// TODO: Should this API even do messaging? It seems like messaging should be
// handled in some other way, or just entirely out-of-band.
// I don't think messaging should even be a part of this in any way.
// Defining a messaging protocol in here is bloat. Using an external messaging
// protocol means double-authentication and increased attack surface.
type MessagingServer interface {
	SendMessage(context.Context, *SendMessageArg) (*SendMessageResult, error)
	ReceiveMessages(context.Context, *ReceiveMessagesArg) (*ReceiveMessagesResult, error)
	DeleteMessage(context.Context, *DeleteMessageArg) (*DeleteMessageResult, error)
	ReadMessage(context.Context, *ReadMessageArg) (*ReadMessageResult, error)
	mustEmbedUnimplementedMessagingServer()
}

// UnimplementedMessagingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessagingServer struct{}

func (UnimplementedMessagingServer) SendMessage(context.Context, *SendMessageArg) (*SendMessageResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessagingServer) ReceiveMessages(context.Context, *ReceiveMessagesArg) (*ReceiveMessagesResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveMessages not implemented")
}
func (UnimplementedMessagingServer) DeleteMessage(context.Context, *DeleteMessageArg) (*DeleteMessageResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMessagingServer) ReadMessage(context.Context, *ReadMessageArg) (*ReadMessageResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMessage not implemented")
}
func (UnimplementedMessagingServer) mustEmbedUnimplementedMessagingServer() {}
func (UnimplementedMessagingServer) testEmbeddedByValue()                   {}

// UnsafeMessagingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagingServer will
// result in compilation errors.
type UnsafeMessagingServer interface {
	mustEmbedUnimplementedMessagingServer()
}

func RegisterMessagingServer(s grpc.ServiceRegistrar, srv MessagingServer) {
	// If the following call panics, it indicates UnimplementedMessagingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Messaging_ServiceDesc, srv)
}

func _Messaging_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).SendMessage(ctx, req.(*SendMessageArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_ReceiveMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveMessagesArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).ReceiveMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_ReceiveMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).ReceiveMessages(ctx, req.(*ReceiveMessagesArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).DeleteMessage(ctx, req.(*DeleteMessageArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_ReadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessageArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).ReadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_ReadMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).ReadMessage(ctx, req.(*ReadMessageArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Messaging_ServiceDesc is the grpc.ServiceDesc for Messaging service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messaging_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.Messaging",
	HandlerType: (*MessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Messaging_SendMessage_Handler,
		},
		{
			MethodName: "ReceiveMessages",
			Handler:    _Messaging_ReceiveMessages_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _Messaging_DeleteMessage_Handler,
		},
		{
			MethodName: "ReadMessage",
			Handler:    _Messaging_ReadMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}

const (
	FinancialAccounts_ListInstitutions_FullMethodName           = "/finsim.FinancialAccounts/ListInstitutions"
	FinancialAccounts_OpenAccount_FullMethodName                = "/finsim.FinancialAccounts/OpenAccount"
	FinancialAccounts_ListAccounts_FullMethodName               = "/finsim.FinancialAccounts/ListAccounts"
	FinancialAccounts_GetAccount_FullMethodName                 = "/finsim.FinancialAccounts/GetAccount"
	FinancialAccounts_CloseAccount_FullMethodName               = "/finsim.FinancialAccounts/CloseAccount"
	FinancialAccounts_SearchTransactions_FullMethodName         = "/finsim.FinancialAccounts/SearchTransactions"
	FinancialAccounts_DisputeTransaction_FullMethodName         = "/finsim.FinancialAccounts/DisputeTransaction"
	FinancialAccounts_CancelTransaction_FullMethodName          = "/finsim.FinancialAccounts/CancelTransaction"
	FinancialAccounts_TransferMoney_FullMethodName              = "/finsim.FinancialAccounts/TransferMoney"
	FinancialAccounts_RequestMoney_FullMethodName               = "/finsim.FinancialAccounts/RequestMoney"
	FinancialAccounts_RequestCreditLimitIncrease_FullMethodName = "/finsim.FinancialAccounts/RequestCreditLimitIncrease"
	FinancialAccounts_ReportFraud_FullMethodName                = "/finsim.FinancialAccounts/ReportFraud"
	FinancialAccounts_RedeemCheck_FullMethodName                = "/finsim.FinancialAccounts/RedeemCheck"
)

// FinancialAccountsClient is the client API for FinancialAccounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinancialAccountsClient interface {
	ListInstitutions(ctx context.Context, in *ListInstitutionsArg, opts ...grpc.CallOption) (*ListInstitutionsResult, error)
	OpenAccount(ctx context.Context, in *OpenAccountArg, opts ...grpc.CallOption) (*OpenAccountResult, error)
	ListAccounts(ctx context.Context, in *ListAccountsArg, opts ...grpc.CallOption) (*ListAccountsResult, error)
	GetAccount(ctx context.Context, in *GetAccountArg, opts ...grpc.CallOption) (*GetAccountResult, error)
	CloseAccount(ctx context.Context, in *CloseAccountArg, opts ...grpc.CallOption) (*CloseAccountResult, error)
	SearchTransactions(ctx context.Context, in *SearchTransactionsArg, opts ...grpc.CallOption) (*SearchTransactionsResult, error)
	DisputeTransaction(ctx context.Context, in *DisputeTransactionArg, opts ...grpc.CallOption) (*DisputeTransactionResult, error)
	CancelTransaction(ctx context.Context, in *CancelTransactionArg, opts ...grpc.CallOption) (*CancelTransactionResult, error)
	TransferMoney(ctx context.Context, in *TransferMoneyArg, opts ...grpc.CallOption) (*TransferMoneyResult, error)
	RequestMoney(ctx context.Context, in *RequestMoneyArg, opts ...grpc.CallOption) (*RequestMoneyResult, error)
	RequestCreditLimitIncrease(ctx context.Context, in *RequestCreditLimitIncreaseArg, opts ...grpc.CallOption) (*RequestCreditLimitIncreaseResult, error)
	ReportFraud(ctx context.Context, in *ReportFraudArg, opts ...grpc.CallOption) (*ReportFraudResult, error)
	RedeemCheck(ctx context.Context, in *RedeemCheckArg, opts ...grpc.CallOption) (*RedeemCheckResult, error)
}

type financialAccountsClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialAccountsClient(cc grpc.ClientConnInterface) FinancialAccountsClient {
	return &financialAccountsClient{cc}
}

func (c *financialAccountsClient) ListInstitutions(ctx context.Context, in *ListInstitutionsArg, opts ...grpc.CallOption) (*ListInstitutionsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstitutionsResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_ListInstitutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) OpenAccount(ctx context.Context, in *OpenAccountArg, opts ...grpc.CallOption) (*OpenAccountResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenAccountResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_OpenAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) ListAccounts(ctx context.Context, in *ListAccountsArg, opts ...grpc.CallOption) (*ListAccountsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountsResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) GetAccount(ctx context.Context, in *GetAccountArg, opts ...grpc.CallOption) (*GetAccountResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) CloseAccount(ctx context.Context, in *CloseAccountArg, opts ...grpc.CallOption) (*CloseAccountResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseAccountResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_CloseAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) SearchTransactions(ctx context.Context, in *SearchTransactionsArg, opts ...grpc.CallOption) (*SearchTransactionsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTransactionsResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_SearchTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) DisputeTransaction(ctx context.Context, in *DisputeTransactionArg, opts ...grpc.CallOption) (*DisputeTransactionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisputeTransactionResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_DisputeTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) CancelTransaction(ctx context.Context, in *CancelTransactionArg, opts ...grpc.CallOption) (*CancelTransactionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransactionResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_CancelTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) TransferMoney(ctx context.Context, in *TransferMoneyArg, opts ...grpc.CallOption) (*TransferMoneyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferMoneyResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_TransferMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) RequestMoney(ctx context.Context, in *RequestMoneyArg, opts ...grpc.CallOption) (*RequestMoneyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestMoneyResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_RequestMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) RequestCreditLimitIncrease(ctx context.Context, in *RequestCreditLimitIncreaseArg, opts ...grpc.CallOption) (*RequestCreditLimitIncreaseResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestCreditLimitIncreaseResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_RequestCreditLimitIncrease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) ReportFraud(ctx context.Context, in *ReportFraudArg, opts ...grpc.CallOption) (*ReportFraudResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportFraudResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_ReportFraud_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountsClient) RedeemCheck(ctx context.Context, in *RedeemCheckArg, opts ...grpc.CallOption) (*RedeemCheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemCheckResult)
	err := c.cc.Invoke(ctx, FinancialAccounts_RedeemCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialAccountsServer is the server API for FinancialAccounts service.
// All implementations must embed UnimplementedFinancialAccountsServer
// for forward compatibility.
type FinancialAccountsServer interface {
	ListInstitutions(context.Context, *ListInstitutionsArg) (*ListInstitutionsResult, error)
	OpenAccount(context.Context, *OpenAccountArg) (*OpenAccountResult, error)
	ListAccounts(context.Context, *ListAccountsArg) (*ListAccountsResult, error)
	GetAccount(context.Context, *GetAccountArg) (*GetAccountResult, error)
	CloseAccount(context.Context, *CloseAccountArg) (*CloseAccountResult, error)
	SearchTransactions(context.Context, *SearchTransactionsArg) (*SearchTransactionsResult, error)
	DisputeTransaction(context.Context, *DisputeTransactionArg) (*DisputeTransactionResult, error)
	CancelTransaction(context.Context, *CancelTransactionArg) (*CancelTransactionResult, error)
	TransferMoney(context.Context, *TransferMoneyArg) (*TransferMoneyResult, error)
	RequestMoney(context.Context, *RequestMoneyArg) (*RequestMoneyResult, error)
	RequestCreditLimitIncrease(context.Context, *RequestCreditLimitIncreaseArg) (*RequestCreditLimitIncreaseResult, error)
	ReportFraud(context.Context, *ReportFraudArg) (*ReportFraudResult, error)
	RedeemCheck(context.Context, *RedeemCheckArg) (*RedeemCheckResult, error)
	mustEmbedUnimplementedFinancialAccountsServer()
}

// UnimplementedFinancialAccountsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialAccountsServer struct{}

func (UnimplementedFinancialAccountsServer) ListInstitutions(context.Context, *ListInstitutionsArg) (*ListInstitutionsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstitutions not implemented")
}
func (UnimplementedFinancialAccountsServer) OpenAccount(context.Context, *OpenAccountArg) (*OpenAccountResult, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenAccount not implemented")
}
func (UnimplementedFinancialAccountsServer) ListAccounts(context.Context, *ListAccountsArg) (*ListAccountsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedFinancialAccountsServer) GetAccount(context.Context, *GetAccountArg) (*GetAccountResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedFinancialAccountsServer) CloseAccount(context.Context, *CloseAccountArg) (*CloseAccountResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseAccount not implemented")
}
func (UnimplementedFinancialAccountsServer) SearchTransactions(context.Context, *SearchTransactionsArg) (*SearchTransactionsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTransactions not implemented")
}
func (UnimplementedFinancialAccountsServer) DisputeTransaction(context.Context, *DisputeTransactionArg) (*DisputeTransactionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DisputeTransaction not implemented")
}
func (UnimplementedFinancialAccountsServer) CancelTransaction(context.Context, *CancelTransactionArg) (*CancelTransactionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTransaction not implemented")
}
func (UnimplementedFinancialAccountsServer) TransferMoney(context.Context, *TransferMoneyArg) (*TransferMoneyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferMoney not implemented")
}
func (UnimplementedFinancialAccountsServer) RequestMoney(context.Context, *RequestMoneyArg) (*RequestMoneyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestMoney not implemented")
}
func (UnimplementedFinancialAccountsServer) RequestCreditLimitIncrease(context.Context, *RequestCreditLimitIncreaseArg) (*RequestCreditLimitIncreaseResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCreditLimitIncrease not implemented")
}
func (UnimplementedFinancialAccountsServer) ReportFraud(context.Context, *ReportFraudArg) (*ReportFraudResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFraud not implemented")
}
func (UnimplementedFinancialAccountsServer) RedeemCheck(context.Context, *RedeemCheckArg) (*RedeemCheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemCheck not implemented")
}
func (UnimplementedFinancialAccountsServer) mustEmbedUnimplementedFinancialAccountsServer() {}
func (UnimplementedFinancialAccountsServer) testEmbeddedByValue()                           {}

// UnsafeFinancialAccountsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialAccountsServer will
// result in compilation errors.
type UnsafeFinancialAccountsServer interface {
	mustEmbedUnimplementedFinancialAccountsServer()
}

func RegisterFinancialAccountsServer(s grpc.ServiceRegistrar, srv FinancialAccountsServer) {
	// If the following call panics, it indicates UnimplementedFinancialAccountsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinancialAccounts_ServiceDesc, srv)
}

func _FinancialAccounts_ListInstitutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstitutionsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).ListInstitutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_ListInstitutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).ListInstitutions(ctx, req.(*ListInstitutionsArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_OpenAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenAccountArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).OpenAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_OpenAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).OpenAccount(ctx, req.(*OpenAccountArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).ListAccounts(ctx, req.(*ListAccountsArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).GetAccount(ctx, req.(*GetAccountArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_CloseAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAccountArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).CloseAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_CloseAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).CloseAccount(ctx, req.(*CloseAccountArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_SearchTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTransactionsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).SearchTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_SearchTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).SearchTransactions(ctx, req.(*SearchTransactionsArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_DisputeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisputeTransactionArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).DisputeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_DisputeTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).DisputeTransaction(ctx, req.(*DisputeTransactionArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_CancelTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransactionArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).CancelTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_CancelTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).CancelTransaction(ctx, req.(*CancelTransactionArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_TransferMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferMoneyArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).TransferMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_TransferMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).TransferMoney(ctx, req.(*TransferMoneyArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_RequestMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMoneyArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).RequestMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_RequestMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).RequestMoney(ctx, req.(*RequestMoneyArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_RequestCreditLimitIncrease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreditLimitIncreaseArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).RequestCreditLimitIncrease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_RequestCreditLimitIncrease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).RequestCreditLimitIncrease(ctx, req.(*RequestCreditLimitIncreaseArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_ReportFraud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFraudArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).ReportFraud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_ReportFraud_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).ReportFraud(ctx, req.(*ReportFraudArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccounts_RedeemCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemCheckArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountsServer).RedeemCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccounts_RedeemCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountsServer).RedeemCheck(ctx, req.(*RedeemCheckArg))
	}
	return interceptor(ctx, in, info, handler)
}

// FinancialAccounts_ServiceDesc is the grpc.ServiceDesc for FinancialAccounts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinancialAccounts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finsim.FinancialAccounts",
	HandlerType: (*FinancialAccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstitutions",
			Handler:    _FinancialAccounts_ListInstitutions_Handler,
		},
		{
			MethodName: "OpenAccount",
			Handler:    _FinancialAccounts_OpenAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _FinancialAccounts_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _FinancialAccounts_GetAccount_Handler,
		},
		{
			MethodName: "CloseAccount",
			Handler:    _FinancialAccounts_CloseAccount_Handler,
		},
		{
			MethodName: "SearchTransactions",
			Handler:    _FinancialAccounts_SearchTransactions_Handler,
		},
		{
			MethodName: "DisputeTransaction",
			Handler:    _FinancialAccounts_DisputeTransaction_Handler,
		},
		{
			MethodName: "CancelTransaction",
			Handler:    _FinancialAccounts_CancelTransaction_Handler,
		},
		{
			MethodName: "TransferMoney",
			Handler:    _FinancialAccounts_TransferMoney_Handler,
		},
		{
			MethodName: "RequestMoney",
			Handler:    _FinancialAccounts_RequestMoney_Handler,
		},
		{
			MethodName: "RequestCreditLimitIncrease",
			Handler:    _FinancialAccounts_RequestCreditLimitIncrease_Handler,
		},
		{
			MethodName: "ReportFraud",
			Handler:    _FinancialAccounts_ReportFraud_Handler,
		},
		{
			MethodName: "RedeemCheck",
			Handler:    _FinancialAccounts_RedeemCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finsim.proto",
}
